### ISSUE TITLE
Android 7.1.2 ,打开相机报错，截图如下：

### ISSUE THREAD

**Issue by RuralPeople** [AnyLifeZLB/FaceVerificationSDK#10]
![image](https://user-images.githubusercontent.com/24812807/216556500-359cc2e4-2937-4586-9daa-b780bc354d9c.png)

**Comment by AnyLifeZLB** [comment]
@RuralPeople  特殊设备还是？如果是手机请告知型号

**Comment by AnyLifeZLB** [comment]
默认是前置摄像头，如果你的手机前置不正常会有这种问题，你也可以配置后置试试。

目前兼容性测试没发现问题

**Comment by AnyLifeZLB** [comment]
更新到3.8.0 后面的版本配置好摄像头
