### ISSUE TITLE
不可以改变底片大小吗？能不能自定义这个相机的框的样式？

### ISSUE THREAD

**Issue by yyy000112** [AnyLifeZLB/FaceVerificationSDK#11]
不可以改变底片大小吗？能不能自定义这个相机的框的样式？

**Comment by AnyLifeZLB** [comment]
改变底片大小是指分辨率吗？这个是可以的，但是对于人脸识别来说不需要太高的分辨率

**Comment by AnyLifeZLB** [comment]
相机框的进度条颜色和提示文字可以修改，你也可以不用FaceCoverView ,自己写一个替换。没有限制的
