### ISSUE TITLE
请问这个方案能商用吗？还是必须授权？有官网吗？

### ISSUE THREAD

**Issue by spysoos** [AnyLifeZLB/FaceVerificationSDK#12]
请问这个方案能商用吗？还是必须授权？有官网吗？

**Comment by AnyLifeZLB** [comment]
@spysoos 跑一下Demo，如果测试验证能符合你的商业项目需求，可以根据ReadMe 要求发送邮件授权。

没官网，所有介绍都会同步到GitHub

**Comment by wuyulu** [comment]
请问商业授权是免费的吗

**Comment by AnyLifeZLB** [comment]
@wuyulu  收点定制服务费，当交个朋友。价格低到没朋友
