### ISSUE TITLE
compileSdk < 33的不能使用吗

### ISSUE THREAD

**Issue by tfl123** [AnyLifeZLB/FaceVerificationSDK#14]

**Comment by AnyLifeZLB** [comment]
可以做到使用，要调整依赖

**Comment by tfl123** [comment]
问题描述

集成io.github.anylifezlb:Face-Verification:3.6.9版本，编译不通过。
gradle:4.1.2，kotlin_version = '1.4.10'，compileSdk 32
错误日志：
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (33) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-32).
        Dependency: androidx.camera:camera-view:1.3.0-alpha02.
        AAR metadata file: /Users/mac/.gradle/caches/transforms-2/files-2.1/67c9e68697bac64b7df5d53f6c703430/jetified-camera-view-1.3.0-alpha02/META-INF/com/android/build/gradle/aar-metadata.properties.
		
Execution failed for JetifyTransform: /Users/mac/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Failed to transform '/Users/mac/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)

手机品牌，型号

平板

Android 系统版本

Android 10

**Comment by tfl123** [comment]
androidx.camera:camera-xxx:1.3.0-alpha02系列组件版本号问题，compileSdk 32的情况下，外部引用如何可以正常使用,如果有方案，麻烦告知一下。

**Comment by AnyLifeZLB** [comment]
@tfl123 预计明早compileSdk 调整32 完成，到时候更新代码

**Comment by AnyLifeZLB** [comment]
@tfl123  
configurations.all {
   //强制使用某个版本的依赖，若需强制多个依赖，可以逗号分割
    resolutionStrategy.force 'com.squareup.okhttp3:okhttp:3.12.0', 'com.squareup.okio:okio:1.17.2'
}

// For example: target 28

 //    def camera_version = '1.1.0-alpha05'      
//    api "androidx.camera:camera-core:$camera_version"
//    api "androidx.camera:camera-camera2:$camera_version"
//    api "androidx.camera:camera-lifecycle:$camera_version"
//    api "androidx.camera:camera-view:1.0.0-alpha25"

**Comment by tfl123** [comment]
感谢作者提供的解决方案，在这个基础之上gradle需要升级到7.0+便可顺利使用。

**Comment by tanbtao** [comment]
请问Android设备 外置usb camera， 如是接入人脸识别功能？

**Comment by AnyLifeZLB** [comment]
@T-b-t  按照下面的方式配置，如果不行那就是不兼容，需要定制化

        // 0 ,前置摄像头       1，后置摄像头    部分外接摄像头支持可能是1
        val cameraXFragment = CameraXAnalyzeFragment.newInstance(CAMERA_ORIGINAL,getSharedPreferences(
            "faceVerify", Context.MODE_PRIVATE).getInt("cameraFlag",0))

**Comment by atclever** [comment]
摄像框能调整焦距吗

**Comment by AnyLifeZLB** [comment]
> 摄像框能调整焦距吗

@atclever 可以的，建议单独提issues 方便跟踪解决问题呢

**Comment by AnyLifeZLB** [comment]
> 摄像框能调整焦距吗

@atclever 可以

第一个参数0/1 指定前后摄像头； 第二个参数linearZoom [0.1f,1.0f] 指定焦距，默认0.1
val cameraXFragment = CameraXFragment.newInstance(0,0.1f)


建议[Fork] + [Star] 关注订阅# [FaceVerificationSDK](https://github.com/AnyLifeZLB/FaceVerificationSDK) 以便获取最新更新消息
