### ISSUE TITLE
照片和照片之间怎么做1:1?

### ISSUE THREAD

**Issue by h3clikejava** [AnyLifeZLB/FaceVerificationSDK#15]
只能用摄像头实时算？

**Comment by AnyLifeZLB** [comment]
@h3clikejava 这个非常简单，SDK 剪裁一下就可以。 只是这个SDK 的场景没考虑这个

**Comment by AnyLifeZLB** [comment]
/**
* 评估两张人脸Bitmap的是否同一人
*
* @param mContext
* @param bitmap1
* @param bitmap2
* @return
*/
public static float evaluateFaceSimi(Context mContext, Bitmap bitmap1, Bitmap bitmap2){}

    //Demo 中已经有如下代码了
    val value=VerifyUtils.evaluateFaceSimi(baseContext,
        VerifyUtils.getBitmapFromAssert(baseContext,"model_1.png"),
        VerifyUtils.getBitmapFromAssert(baseContext,"model.jpg"))

    Log.d("VerifyUtils", "value:  $value")
不管什么图只要转为Bitmap ，你可以在Assert 目录放2张图测试一下

V 1.3.4 开始支持 ,更新Demo
