### ISSUE TITLE
源码中没有MobileFaceNet，程序跑不起

### ISSUE THREAD

**Issue by ysheng88** [AnyLifeZLB/FaceVerificationSDK#2]
源码中没有MobileFaceNet，程序跑不起

**Comment by AnyLifeZLB** [comment]
@ysheng88 有没有可能是你的网络同步不了依赖，建议
1.更新到最新代码
2.开启科学翻墙 看看能否同步 implementation "io.github.anylifezlb:Face-Verification:1.0.0-alpha02"

如果还有问题请贴错误日志，谢谢
