### ISSUE TITLE
下一阶段优化汇总.

### ISSUE THREAD

**Issue by AnyLifeZLB** [AnyLifeZLB/FaceVerificationSDK#22]
1. 摄像头预览的分辨率和分析的分辨率调大到接近1080 P
2.画面中的人脸检测灵敏度调整大于120*120 即可
3.提供一个两张人脸图片相识度方案，包括自动裁剪出人脸
4.人脸搜索可以不仅仅是摄像头采集数据，支持Camera,RTSP和单张图Bitmap

**Comment by WendellHe** [comment]
能否加上服务端运行的sdk呢。前端提取特征，后端进行对比搜索。

**Comment by huaxuanHan** [comment]
感谢大佬的辛苦付出

**Comment by AnyLifeZLB** [comment]
RTSP 的需要再研究一下怎么取单帧数据分析
