### ISSUE TITLE
编译不通过, aar包无法下载

### ISSUE THREAD

**Issue by 1996cy** [AnyLifeZLB/FaceVerificationSDK#23]
在build项目时报错;

org.gradle.api.resources.ResourceException: Could not get resource 'https://repo.maven.apache.org/maven2/org/tensorflow/tensorflow-lite/2.11.0/tensorflow-lite-2.11.0.aar'.
还有一个FaceRecognition-1.2.2.aar , 这两个包无法下载, 尝试多次仍然无果

机型: 小米10pro
android版本: 12     miui13

**Comment by 1996cy** [comment]
另外点击链接跳转到网页下载aar包是可以下载成功的, 但是仍然会多次下载失败才能下完

**Comment by AnyLifeZLB** [comment]
https://repo.maven.apache.org/maven2/org/tensorflow/tensorflow-lite/2.11.0/tensorflow-lite-2.11.0.aar 这个链接你直接点击可以下载吗？ 可能部分公司内网会屏蔽

**Comment by 1996cy** [comment]
点这个链接可以下载, 但是下载到后面进度就卡住了, 然后下载失败

**Comment by lief93** [comment]
可以直接提供这几个包吗，挂了VPN也下不下来
