### ISSUE TITLE
SourceTree拉代码时报错

### ISSUE THREAD

**Issue by zkteco-home** [AnyLifeZLB/FaceVerificationSDK#25]
![image](https://github.com/AnyLifeZLB/FaceVerificationSDK/assets/66519168/6a3db8c7-9ec0-41f0-a65a-d87fcddc6b69)

**Comment by AnyLifeZLB** [comment]
@zkteco-home 文件命名字符编码有问题，我改一下文件名

**Comment by zkteco-home** [comment]
没问题了，非常感谢，先测试下，我是用作移动考勤，可惜不支持ios.
