### ISSUE TITLE
DEMO效果很好，就是跑不起来

### ISSUE THREAD

**Issue by lief93** [AnyLifeZLB/FaceVerificationSDK#27]
直接编译sdk
compileSdkVersion 33
gradle插件 7.3.1
gradle 7.4
提示
```
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.vanniktech.maven.publish.base:com.vanniktech.maven.publish.base.gradle.plugin:0.24.0: Skipped due to earlier error
``` 
另外gradle升级到7是不是很多依赖要跟着要做适配，直接依赖1.2.2提示
```
Unable to find method ''java.lang.String com.android.utils.FileUtils.relativePossiblyNonExistingPath(java.io.File, java.io.File)''
'java.lang.String com.android.utils.FileUtils.relativePossiblyNonExistingPath(java.io.File, java.io.File)'
``` 
compile sdk和gradle版本可以降吗，麻烦帮忙看下

**Comment by AnyLifeZLB** [comment]
你是直接跑Demo 出的问题吗？ 如果是的话我把我本地工程清除重新试试

**Comment by AnyLifeZLB** [comment]
https://vanniktech.github.io/gradle-maven-publish-plugin/central/   是不是你公司内网屏蔽了相关网址访问 ？

**Comment by lief93** [comment]
> 你是直接跑Demo 出的问题吗？ 如果是的话我把我本地工程清除重新试试

是的，直接跑的demo

**Comment by lief93** [comment]
> https://vanniktech.github.io/gradle-maven-publish-plugin/central/ 是不是你公司内网屏蔽了相关网址访问 ？ @lief93

没有屏蔽哦，网址能打开。我试了下老版本的代码可以编译通过

**Comment by lief93** [comment]
请问sdk的源码是不对外公布吗，因为我的需求是在人脸识别的时候还要推送音视频流，估计会有摄像头冲突，所以想改动下

**Comment by lief93** [comment]
现在依赖1.2.2可以编译了，之前报错
```
Unable to find method ''java.lang.String com.android.utils.FileUtils.relativePossiblyNonExistingPath(java.io.File, java.io.File)''
'java.lang.String com.android.utils.FileUtils.relativePossiblyNonExistingPath(java.io.File, java.io.File)'
``` 
是因为跟matrix有冲突，应该修改matrix版本可以解决。我暂时注释掉了，之前百度这个错误的时候有些库回答是没适配gradle7.0，需要对应库升级

**Comment by lief93** [comment]
人脸识别的时候会提示一个alpha sdk version，请问这个是要付费才能去掉的吗

**Comment by AnyLifeZLB** [comment]
你好，我们邮件或WEChat 联系
