### ISSUE TITLE
Alpha SDK Version

### ISSUE THREAD

**Issue by tfl123** [AnyLifeZLB/FaceVerificationSDK#28]
1:1人脸识别时会出现“Alpha SDK Version”提示
1:1人脸识别通过后会出现“阀值范围的提示”，这个提示应该是在sdk里写的？这个提示sdk里能否去掉

**Comment by AnyLifeZLB** [comment]
你是使用的哪个版本SDK ？ @tfl123

**Comment by tfl123** [comment]
io.github.anylifezlb:FaceRecognition:1.2.2这个版本，直接运行git上的代码也会出现“Alpha SDK Version”提示，
工程 compileSdkVersion 33，设备：HUAWEI M6，型号：SCM-W09，Android10

**Comment by AnyLifeZLB** [comment]
@tfl123 调试信息 你依赖1.2.5 去掉了，大概30分钟同步好

**Comment by tfl123** [comment]
io.github.anylifezlb:FaceRecognition:1.2.5更新不了呢 @AnyLifeZLB
