### ISSUE TITLE
SourceTree PUll error

### ISSUE THREAD

**Issue by zkteco-home** [AnyLifeZLB/FaceVerificationSDK#29]
![image](https://github.com/AnyLifeZLB/FaceVerificationSDK/assets/66519168/894bdabd-9bc8-4884-9ff0-0ac088c6ea1a)

**Comment by AnyLifeZLB** [comment]
error: invalid path 'res/M:N_Test.jpg'

This issue has been resolved, try again

**Comment by zkteco-home** [comment]
Thanks,working fine now
