### ISSUE TITLE
如何支持多国语言？

### ISSUE THREAD

**Issue by zkteco-home** [AnyLifeZLB/FaceVerificationSDK#30]
你好，我正在关注和测试该项目，活体检测时的文字和语音提示都是SDK内部固定信息，请问如果我要开发支持多国语言，怎么办呢？建议开放更多的参数，比如增加参数用于检测的文字，增加参数用于控制动作数，是否需要语音提示？比如如果我只需要一个动作，我可以控制。

**Comment by AnyLifeZLB** [comment]
@zkteco-home 你好，我们下周一会上线一版本国际化SDK，请关注更新

**Comment by AnyLifeZLB** [comment]
目前提示语和语音都放开了，在Demo 中，你可以根据Google 官方说明放不同的语言。

至于语音提示，不建议和Demo 一样放一个个文件（仅供参考演示），你可以使用文字（多语言）转语音服务

**Comment by zkteco-home** [comment]
好，谢谢。
