### ISSUE TITLE
可否直接支持jpg图像比对？

### ISSUE THREAD

**Issue by zkteco-home** [AnyLifeZLB/FaceVerificationSDK#31]
JPG PNG格式的图像比较流行，可否考虑增加支持jpg图像比对？

**Comment by AnyLifeZLB** [comment]
可以，支持中

**Comment by AnyLifeZLB** [comment]
//测试两张人脸是否相同  model.jpg
        val value=VerifyUtils.evaluateFaceSimi(baseContext,
            VerifyUtils.getBitmapFromAssert(baseContext,"model_1.png"),
            VerifyUtils.getBitmapFromAssert(baseContext,"model.jpg"))

        Log.d("VerifyUtils", "value:  $value")


 转为Bitmap ，你可以在Assert 目录放2张图测试一下

V 1.3.3 开始支持

**Comment by zkteco-home** [comment]
看到Demo了，感谢你们的付出。React native比较流行，我先封装下用于React native的库，看看会遇到什么困难再反馈。

**Comment by AnyLifeZLB** [comment]
@zkteco-home 封装好了方便贴个链接，我在主页放个跳转作为指导。谢谢
