### ISSUE TITLE
我说没什么用，还把我的问题删了？

### ISSUE THREAD

**Issue by cwwei2005** [AnyLifeZLB/FaceVerificationSDK#33]

**Comment by AnyLifeZLB** [comment]
你连提issues 都不明白怎么操作？你在另外一个库提的，我把他关闭了又来这里。你倒是封装一个有用的
你从你的主页看不到活动Activity ???  我是抢了你的生意还是拦截了你的客户 ？？

![image](https://github.com/AnyLifeZLB/FaceVerificationSDK/assets/15169396/d05df56a-6b76-482b-b478-76faa0205c8b)

**Comment by AnyLifeZLB** [comment]
能看明白你在不同的库提的Issues，因为什么被关闭了吗

**
![image](https://github.com/AnyLifeZLB/FaceVerificationSDK/assets/15169396/cc4fc36a-80bb-471b-9646-053a0d75932e)
**
