### ISSUE TITLE
demo编译失败

### ISSUE THREAD

**Issue by 1996cy** [AnyLifeZLB/FaceVerificationSDK#39]
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.vanniktech.maven.publish.base:com.vanniktech.maven.publish.base.gradle.plugin:0.25.3
Could not get resource 'https://repo.maven.apache.org/maven2/com/vanniktech/maven/publish/base/com.vanniktech.maven.publish.base.gradle.plugin/0.25.3/com.vanniktech.maven.publish.base.gradle.plugin-0.25.3.jar'.
Could not HEAD 'https://repo.maven.apache.org/maven2/com/vanniktech/maven/publish/base/com.vanniktech.maven.publish.base.gradle.plugin/0.25.3/com.vanniktech.maven.publish.base.gradle.plugin-0.25.3.jar'.
repo.maven.apache.org

这个0.25.3.jar找不到了, 试了科学上网还是不行, 请问怎么解决

**Comment by AnyLifeZLB** [comment]
@1996cy 是否浏览器中能访问

https://repo.maven.apache.org/maven2/com/vanniktech/maven/publish/base/com.vanniktech.maven.publish.base.gradle.plugin/0.25.3/com.vanniktech.maven.publish.base.gradle.plugin-0.25.3.pom

**Comment by 1996cy** [comment]
> @1996cy 是否浏览器中能访问
> 
> https://repo.maven.apache.org/maven2/com/vanniktech/maven/publish/base/com.vanniktech.maven.publish.base.gradle.plugin/0.25.3/com.vanniktech.maven.publish.base.gradle.plugin-0.25.3.pom
这个可以访问

**Comment by 1996cy** [comment]
@AnyLifeZLB 能访问

**Comment by AnyLifeZLB** [comment]
那就说明服务没问题，可能是你的Android Studio 有代理设置不对？ @1996cy

**Comment by 1996cy** [comment]
jar那个链接我浏览器打开也是404, 我想手动导入也没办法

**Comment by AnyLifeZLB** [comment]
奇怪，    implementation 'com.vanniktech.maven.publish.base:com.vanniktech.maven.publish.base.gradle.plugin:0.25.3'

这是Maven Publish 的东西，我这里都没问题，明天我升级
