### ISSUE TITLE
有计划鸿蒙版本的么

### ISSUE THREAD

**Issue by w296365959** [AnyLifeZLB/FaceVerificationSDK#44]

**Comment by AnyLifeZLB** [comment]
@w296365959 SDK V1.8.50 已经测试通过为当前稳定版本，根据SDK 接入DEMO 集成到你的主工程。

也可以直接下载APK 体验一下 https://www.pgyer.com/faceVerify。

**Comment by AnyLifeZLB** [comment]
当前市场的鸿蒙系统是支持的，https://www.pgyer.com/faceVerify 能跑起来就支持。NEXT 兼容计划看市场反应

**Comment by FaceAISDK** [comment]
手机安装就可以体验效果，https://www.pgyer.com/faceVerify 。2025 09 10
