### ISSUE TITLE
jdk不兼容：this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by JiangShuLiang** [AnyLifeZLB/FaceVerificationSDK#48]
依赖后，提示如下：
![微信截图_20241115182700](https://github.com/user-attachments/assets/16163c5b-749c-4f90-936c-9abf019e66de)

Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

我自己的项目本身jdk版本就是1.8的
![微信图片_20241115182612](https://github.com/user-attachments/assets/0517a14b-ed3c-47fd-baeb-bf0eb63d056b)
![微信图片_20241115182616](https://github.com/user-attachments/assets/39b308a3-6a58-4e1d-8525-8861acbd0c16)

**Comment by AnyLifeZLB** [comment]
@JiangShuLiang  先更新git demo . 升级版本到1.8.50 
下周一如果还没回复你解决方案请发邮件到anylife.zlb@gmail.com

**Comment by AnyLifeZLB** [comment]
@JiangShuLiang 
 先更新git demo 代码 . SDK 升级版本到1.8.50 
java version==11

下周一如果还没解决方案请发邮件到anylife.zlb@gmail.com 

<img width="1280" alt="截屏2024-11-17 20 39 09" src="https://github.com/user-attachments/assets/cd18b7a1-6b66-4221-b19a-5690e2682fce">

**Comment by JiangShuLiang** [comment]
> @JiangShuLiang 先更新git demo 代码 . SDK 升级版本到1.8.50 java version==11
> 
> 下周一如果还没解决方案请发邮件到[anylife.zlb@gmail.com](mailto:anylife.zlb@gmail.com)
> 
> <img alt="截屏2024-11-17 20 39 09" width="1280" src="https://private-user-images.githubusercontent.com/15169396/386957799-cd18b7a1-6b66-4221-b19a-5690e2682fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTIxNTYsIm5iZiI6MTczMTg5MTg1NiwicGF0aCI6Ii8xNTE2OTM5Ni8zODY5NTc3OTktY2QxOGI3YTEtNmI2Ni00MjIxLWIxOWEtNTY5MGUyNjgyZmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAxMDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzY1M2NhYWNiMWNmMzM3NzRjZmRmNzcyN2FiNTg1NGQ1NWE5MGU3NzEwY2Q0MjU5YjI4OWM3MmE0MjIwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S0K2NNWi8cWCZMzscFo9-M71LLXhFW4ApFJze4Z2Lig">

这个jdk问题是解决了，但又有新的问题，如下图所示：

**Comment by AnyLifeZLB** [comment]
@JiangShuLiang 

如下操作后翻墙下载同步依赖

![image](https://github.com/user-attachments/assets/79b1202e-bf62-4ef2-b3bb-c8124ab5cfe7)

**Comment by AnyLifeZLB** [comment]
这里gradle 也要改，



![image](https://github.com/user-attachments/assets/ccec2adc-32ae-4805-8bf5-de1024126a0f)
