### ISSUE TITLE
缓存的图片为0字节无法裁剪

### ISSUE THREAD

**Issue by zhushenwudi** [AnyLifeZLB/FaceVerificationSDK#5]
![iShot_2022-09-06_12 34 13](https://user-images.githubusercontent.com/30340027/188590555-d72a873a-2377-4bb4-a8cb-3c3ea1bcd0fa.png)
![iShot_2022-09-06_12 34 21](https://user-images.githubusercontent.com/30340027/188590563-f2e0e3a2-9ab1-4fb2-ac1e-42bdf486ead5.png)
![iShot_2022-09-06_12 34 29](https://user-images.githubusercontent.com/30340027/188590582-fe8e422d-9164-4a44-82d7-b284e3de291e.png)

**Comment by AnyLifeZLB** [comment]
@zhushenwudi 你的系统版本号是多少？ 对应版本的手机也有吗？

**Comment by zhushenwudi** [comment]
开发板rk3288 android7.1.2

**Comment by AnyLifeZLB** [comment]
这个应该是开发板烧录的系统的裁剪器有问题，底片裁剪代码【完全是开放】的，你可以根据系统特性选择合适的方式裁剪

**Comment by AnyLifeZLB** [comment]
有没有对比虹软的识别性能数据，SDK 大小，初始化速度，识别速度等，有的话麻烦告知一下，谢谢！

**Comment by AnyLifeZLB** [comment]
> 开发板rk3288 android7.1.2 armv7，测试的小米手机目前没有问题

真机验证了所有的7.1.2 的系统没有发现此问题，
这个应该是开发板烧录的系统的裁剪器有问题，底片裁剪代码【完全是开放】的，你可以根据系统特性选择合适的方式裁剪

**Comment by zhushenwudi** [comment]
好的
