### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by shehuan** [AnyLifeZLB/FaceVerificationSDK#52]
![image](https://github.com/user-attachments/assets/119a59e6-c1d3-47e9-a850-79fd6c608b53)

**Comment by AnyLifeZLB** [comment]
@shehuan 你好，Silent Engine 无法依赖，点击对应的链接浏览器是否能打开？

多添加几个依赖源试试 ，还没解决加我微信

       maven {url "https://maven.aliyun.com/nexus/content/groups/public/"}
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
