### ISSUE TITLE
runSearch识别失败

### ISSUE THREAD

**Issue by ly-alan** [AnyLifeZLB/FaceVerificationSDK#57]
GuardFragment: runSearch
12-05 11:07:09.437  2725  3040 I GuardFragment: imageProxy= 960 : 540 : 35 : {"bottom":540,"left":0,"right":960,"top":0}
12-05 11:07:09.532  2725  3040 D skia    : onFlyCompress
12-05 11:07:09.570  2725  3040 D skia    : JPEG Decode 17
12-05 11:07:09.591  2725  3040 I tflite  : Replacing 26 out of 29 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions for the whole graph.
12-05 11:07:09.607  2725  3040 I tflite  : Replacing 26 out of 29 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions for the whole graph.
12-05 11:07:09.617  2725  3040 I tflite  : Replacing 26 out of 29 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions for the whole graph.
12-05 11:07:09.623  2725  3040 I tflite  : Replacing 26 out of 29 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions for the whole graph.
12-05 11:07:09.627  2725  3040 I tflite  : Replacing 26 out of 29 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions for the whole graph.
12-05 11:07:09.642  2725  3040 I tflite  : Replacing 34 out of 37 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions for the whole graph.
12-05 11:07:09.659  2725  3040 W System.err: java.lang.IllegalArgumentException: Array lengths cannot be 0.
12-05 11:07:09.659  2725  3040 W System.err: 	at org.tensorflow.lite.TensorImpl.computeNumDimensions(TensorImpl.java:368)
12-05 11:07:09.659  2725  3040 W System.err: 	at org.tensorflow.lite.TensorImpl.computeShapeOf(TensorImpl.java:334)
12-05 11:07:09.659  2725  3040 W System.err: 	at org.tensorflow.lite.TensorImpl.getInputShapeIfDifferent(TensorImpl.java:263)
12-05 11:07:09.659  2725  3040 W System.err: 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:251)
12-05 11:07:09.659  2725  3040 W System.err: 	at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:101)
12-05 11:07:09.659  2725  3040 W System.err: 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:95)
12-05 11:07:09.659  2725  3040 W System.err: 	at I1I.IL1Iii.Companion(SourceFile)
12-05 11:07:09.659  2725  3040 W System.err: 	at I1I.IL1Iii.Companion(SourceFile)
12-05 11:07:09.660  2725  3040 W System.err: 	at I1I.IL1Iii.Companion(SourceFile)
12-05 11:07:09.660  2725  3040 W System.err: 	at iI丨LLL1.ILil.Companion(SourceFile)
12-05 11:07:09.660  2725  3040 W System.err: 	at iI丨LLL1.ILil.Companion(SourceFile)
12-05 11:07:09.660  2725  3040 W System.err: 	at com.ai.face.faceSearch.search.FaceSearchEngine.runSearch(SourceFile)

前置摄像头，1.8.28版本

**Comment by AnyLifeZLB** [comment]
@ly-alan 你好参考本工程升级到1.8.62 。1.8.28版本有Bug，差异太大了

**Comment by ly-alan** [comment]
刚刚试了1.8.62的还是一样的错误。这个错误可以被trycatch捕获了

**Comment by AnyLifeZLB** [comment]
你用我的Demo SDK接入工程跑在手机会有这个问题吗？你排查一下。报这个错说明画面中没有检测到人脸

**Comment by ly-alan** [comment]
@AnyLifeZLB 这个是一个杂牌的平板，也不知道具体型号。
我用手机没问题。
没检测到人脸，我感觉正常处理流程是在ProcessCallBack里面回调错误，而不是直接异常后停止整个识别过程，也不会出现相机预览
