### ISSUE TITLE
双目摄像头无法获取相机信息，只能打开黑白摄像头

### ISSUE THREAD

**Issue by zhushenwudi** [AnyLifeZLB/FaceVerificationSDK#6]
![iShot_2022-09-06_16 48 16](https://user-images.githubusercontent.com/30340027/188590833-e06e03d4-b0b3-49bb-b2f6-549b17e5ca27.png)

**Comment by AnyLifeZLB** [comment]
双目摄像头，我看了一下，手上没有设备可以复现，暂时处理不了
